firemorey:
  pic:
    url: http://senyer.club
    path: /usr/local/src/project/szx-web/back-end/img/

server:
  servlet:
    context-path: /
  port: 9527
  tomcat:
    max-http-post-size: 10000000

#logback自定义路径配置
logback:
  logdir: /var/firemorey/log
  appname: ChinaNo1
#mybatis-plus相关配置
mybatis-plus:
  mapper-locations: classpath*:mappers/*.xml
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

#多数据源配置
spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      datasource:
        master:
          username: root
          password: Senyer@3141592657
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://senyer-remote.mysql.rds.aliyuncs.com:3306/firemorey?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8
        sqlve:
          username: root
          password: Senyer@3141592657
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://senyer-remote.mysql.rds.aliyuncs.com:3306/firemorey?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8
